### ISSUE TITLE
Improve OsX (and maybe Linux) compatibility 

### ISSUE THREAD

**Issue by jasonswearingen** [NotNotTech/Raylib-CsLo#1]
**EDIT**:  I believe that the Nuget package now contains full linux (ubuntu 20.04).   However full OsX support needs the xcode project compiled and submitted in a pr.    

<del>
Building from source should also work in the same way as nuget.  Internally the wrapper will search for `raylib-with-extras` but if that is not present, it will look for `raylib` itself.      This is how OsX can be partially supported (right now `raylib-cslo` uses the `libraylib.dylib` from the raylib 4.0 release)   

If you do build `raylib-with-extras` you will need to put them in the proper folder under the built binaries (under `./runtimes/*/native/`) , as the `raylib-cslo` binary now has code to automatically looks for the binaries.  (see commit: https://github.com/NotNotTech/Raylib-CsLo/commit/29f6ad61654100ff39f49d3c31af5faebc8a8a99)     If you do so, please consider submitting a PR with the built binaries for others to use.      

</del>

**EDIT2: 2022-02-10:**  The above native assembly picking was disabled, so that NetStandard2.1 can be supported.  The above required Net6.     Now all native code is built into a single `raylib.dll`.   The native project to create this is checked in at the same location under the `sub-modules` folder.

Original message below just in case there is useful info to you, please note this was written before consolidating native binaries into a single `raylib-with-extras`.

> 
> There are reports that linux compatibility is not a simple act of "replace raylib.dll with the linux version"
> 
> This is a summary of the issues from my understanding.   As I do not have a linux desktop, I can not verify nor fix any issues with linux right now.  **If you are capable, please consider contributing a solution to this**
> 
> - linux doesn't use `.dll` for shared libraries.  it uses `.so`     
>   - the dotnet native pinvoke bindings reference `raylib.dll` directly by name.   so something has to be done here (maybe just rename the linux binaries?)
> - the existing nuget package is for windows only.   can this be turned into a cross-platform package?
> - whatever is the solution for `raylib.dll`, the same solution is needed for `raygui.dll` and `physac.dll`
> 
> This repository includes a Visual Studio `C` solution+project for `raygui` and `physac`, and directly links the `raylib` repo (as a sub-module) so it can be built too.    This is how the windows `dll`'s are created.  If a PR can be submitted that can alter this workflow to work for linux binaries, that would be great.   I don't think bindings gen has to change, just the native dll build process.
> 
> There is a similar issue with `raylib-cs`:  https://github.com/ChrisDill/Raylib-cs-Examples/issues/14
> 
> The best solution is for this work to be done in a real desktop linux environment, but it may be possible on windows via WSL.   if using WSL be aware that you need to set up X forwarding for the gui to not crash.    Perhaps see this SO question for more info: https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2
>

**Comment by jasonswearingen** [comment]
I think the fix should be pretty straight forward for a linux dotnet+c developer.    However as I have no linux desktop or build experience, I think that all of this combined represents a full day of work for me (if I'm lucky), and is not related to any of my current goals so I can't justify doing it any time soon.    When I get a game prototype done, then hopefully someone else will have contributed a solution, otherwise I'll do it then.   

Sorry, I just want to be honest 😦

**Comment by adamdusty** [comment]
Confirmed working on Arch. Specifically the example in the readme. Before I mentioned it on discord, I couldn't even compile the readme example.

**Comment by jasonswearingen** [comment]
Thanks for the feedback Adam.   I added some notes on that in the readme.

Still need validation on osx, if anyone is up for it.   Additionally, to use `raygui` or `physac` It will require compiling the xcode project.

**Comment by jasonswearingen** [comment]
superseded by #23
