### ISSUE TITLE
RayGui methods not working

### ISSUE THREAD

**Issue by ZackaryH8** [NotNotTech/Raylib-CsLo#14]
When I'm trying to call a `RayGui` method, I get this error in the console. Did I massively overlook something?

### Code
```csharp
using Raylib_CsLo;

namespace PixelArtGame
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Raylib.InitWindow(800, 480, "PixelArtGame");
            RayGui.GuiLoadStyleDefault();
        }
    }
}
```

### Error
```
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'GuiLoadStyleDefault' in DLL 'raylib'.
   at Raylib_CsLo.RayGui.GuiLoadStyleDefault()
   at CircleClicker.Program.Main(String[] args) in .\PixelArtGame\Program.cs:line 16

.\PixelArtGame\bin\Debug\net6.0\PixelArtGame.exe (process 12292) exited with code -532462766.
```

**Comment by jasonswearingen** [comment]
You need to build a custom Raylib.dll that includes the extras.    You can see the checked in `.c` files here for what needs to be added
https://github.com/NotNotTech/Raylib-CsLo/tree/main/sub-modules/raylib-with-extras/src

**Comment by jasonswearingen** [comment]
also fyi I tried to include my build notes here: https://github.com/NotNotTech/Raylib-CsLo/tree/main/sub-modules
That's the first time I ever had to build C stuff, so probably not "optimal" but it worked for windows+linux.

**Comment by ZackaryH8** [comment]
Yeah I got it all working now, thanks!
