### ISSUE TITLE
NuGet Package for Raspberry Pi (32bit)

### ISSUE THREAD

**Issue by hanlectin** [NotNotTech/Raylib-CsLo#15]
Hi!
I have been using raylib-cs so far. But it would be nice to have RayGui, too... so I thought of switching to Raylib-CsLo...
any chance of adding the binaries for Raspberry Pi (32bit) to the nuget package?
or maybe some tutorial on how to build raylib-cslo on the Pi?
has anyone done it already?

thanks

**Comment by jasonswearingen** [comment]
Hi Sorry I have no idea how to build for the pi.  I assume it runs some form of linux?  If so, you can fork this repository and follow the instructions found here: https://github.com/NotNotTech/Raylib-CsLo/tree/main/sub-modules to build a 32bit version of the native raylib.dll (which will include raygui)

Then if you build raylib-cslo (not ue the nuget package) and copy the native raylib.dll to the output folder, it should work.

If this does work, you can submit a PR with the raspberry pi binary, or send it to me directly, and I'll add it to the nuget package for others.

**Comment by hanlectin** [comment]
it actually turned out to be pretty simple:
up until now, I compiled raylib (the C++ stuff) like I read in the TODO here: https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi (to get a libraylib.so)
> make PLATFORM=PLATFORM_DRM RAYLIB_LIBTYPE=SHARED

but I found, there is a parameter "RAYLIB_MODULE_RAYGUI"; so adding that adds the raygui-code to libraylib.so:
> make PLATFORM=PLATFORM_DRM RAYLIB_MODULE_RAYGUI=TRUE RAYLIB_LIBTYPE=SHARED

--> using raylib-cslo I can now use everything from within C# (dotnet 6.0 that is). cool :)

...but I think we cannot easily add the binaries for the Pi to the nuget-package, as there are multiple options for the Pi:
(see https://github.com/raysan5/raylib/wiki/Working-on-Raspberry-Pi)
a1) Pi0-3
a2) Pi4
b1) native mode "DRM" (OpenGL ES 2.0 - no X11 required) //I use this
b2) OpenGL on X11
--> so I guess it's up to the end-user to decide which one to use and compile raylib individually!
