### ISSUE TITLE
LoadFontEx needs unsafe to be used.

### ISSUE THREAD

**Issue by SoloByte** [NotNotTech/Raylib-CsLo#16]
The "char *fileName" was already replaced with a string variant but the "int *fontChars" is still there so unsafe needs to be used... There are probably some other font functions that have the same problem but I only use LoadFontEx. (I am using Raylib CsLo for 2d only)

Here is the function from Raylib:

- LoadFontEx(const char *fileName, int fontSize, int *fontChars, int glyphCount); 

And that is the function from Raylib-CsLo

- LoadFontEx(string fileName, int fontSize, int* fontChars, int glyphCount);

Thanks for the awesome work with the bindings :)

**Comment by jasonswearingen** [comment]
sorry I am only now getting to this.    

All the examples I have using `LoadFontEx()`  pass `(int*)0` to it, so I'm not sure what expected values are.

To satisfy your ask, I have added the following safe override you can use instead:
```cs
public static Font LoadFontEx(string fileName, int fontSize,  int glyphCount) =>LoadFontEx(fileName, fontSize,default(int*), glyphCount);
```

basically letting you omit the `fontChars` argument.   

This will be in the upcomming `4.2.0-alpha1` preview nuget release (a little later today)
