### ISSUE TITLE
Null string conversion

### ISSUE THREAD

**Issue by veins1** [NotNotTech/Raylib-CsLo#17]
Wherever null string is accepted it is converted to a valid pointer to a '\0' instead of null.
This produces a warning when using LoadShader since '\0' is not a valid file path but at least it works since raylib checks if file was loaded correctly.
This completely breaks LoadShaderFromMemory however because it's trying to compile '\0' as a shader.

**Comment by jasonswearingen** [comment]
Do you have some sample code I could test with?  probably the string marshalling helper needs to be modified.  But I'm not an expert on marshalling so having an explcit sample code to verify with would help.

**Comment by jasonswearingen** [comment]
related to #20

**Comment by jasonswearingen** [comment]
this has been fixed.  `4.2 alpha1` should have the fix (later today).  please track #20 for more details.
