### ISSUE TITLE
ExportWaveAsCode/ExportImageAsCode do not work as expected because they export as an .h file.

### ISSUE THREAD

**Issue by SoloByte** [NotNotTech/Raylib-CsLo#18]
ExportWaveAsCode/ExportImageAsCode functions are meant to export to an .h file which is not directly usable in c# ... Is there any way to fix this with the bindings?

**Comment by jasonswearingen** [comment]
a `.h` file can be added to the binding generation workflow, what is the .h file you need?

**Comment by SoloByte** [comment]
My point was that Export...AsCode functions do not make much sense if the export .h files in a c# project. 

I wanted to make a system where I have all the resources packed into the source code for distribution but because of the rres system I don´t need to do that anymore ;)

I do not think that you can actually change how they export a file anyway, right? You can close this issue if you want.

**Comment by jasonswearingen** [comment]
okay yeah I will look at rres this weekend.
