### ISSUE TITLE
Raylib 4.2 is already out, do you plan in supporting it or are u even already on the process?

### ISSUE THREAD

**Issue by CodingMadness** [NotNotTech/Raylib-CsLo#21]
Title :)

4.2 is quite some major release, I really would love to encourage you keeping it continuosly up to date, its really worth this library especially having it with .net 7 now :D

**Comment by jasonswearingen** [comment]
thanks for pinging this! I didn't know about the `4.2` release actually.  I should be able to schedule time to update this coming weekend.  

However if you wanted to give porting a try, the entire process+docs are in this repo, I'd be happy with a PR!  If not, please feel free to ping me next week if I haven't gotten to it yet!

**Comment by CodingMadness** [comment]
@jasonswearingen  Hey, would be super good cause raylib really needs to be C# usable at all cost and also please keep in mind to change from .netstandard 2.1 to .net 7 in the settings!

**Comment by jasonswearingen** [comment]
ok i'll take a look.    btw what's wrong with NetStandard 2.1?  You can reference that from a net7 project no problem.

**Comment by CodingMadness** [comment]
> 

Its just .net 7 is simply by default a BEAST, without any coding. And since .net X will be the standard for all platforms sinc .net 5, its a good idea generally to upgrade that to the most recent version :)

**Comment by CodingMadness** [comment]
@jasonswearingen  If you agree on changing from .netstandard build for your raylib-CsLo project to .net X, use .net6 as it is the most stable one, was a bad idea from me to suggest using .net 7 which is still in preview and can have bugs and so.. so better do not use that..

**Comment by CodingMadness** [comment]
@jasonswearingen Jason, may i ask, are u already on it? Like updating to 4.2? Would be cool to know , cheers!

**Comment by jasonswearingen** [comment]
I wasn't able to get to it on the weekend sadly!  My hope is this week but weekend at latest.

**Comment by CodingMadness** [comment]
@jasonswearingen dont worry man, I am just wondering, take ur time.  I was abit annoying and for that I wanna appologize!

Keep up the great work and have fun doing it :-)

**Comment by jasonswearingen** [comment]
i took a look today, this is going to take at least a few hours because the non-core features like physac and raygui are no longer in the raylib repository.  I'll need more time (on weekend)

**Comment by CodingMadness** [comment]
BTW: I am wondering right now by using your raybinding; Why are u having all these Colors "RED, WHITE" in  Raylib and not in the Color struct as readonlys? 

its more cleaner to write: Color.RED than Raylib.RED I find

**Comment by jasonswearingen** [comment]
It's because the bindings are auto-generated, and that's how it is in the
raylib c++ library.raylib-cs does hand-rolled customization to make it
nicer, raylib-cslo is all autogenerated.   On a positive note, it should be
really easy to update to 4.2!   I just wasn't aware of the update till last
week.

 - Jason

**Comment by CodingMadness** [comment]
@jasonswearingen  So can u do it today?

**Comment by jasonswearingen** [comment]
I have mostly completed the work and tested on Win x64.  see the "4.2-update" branch.   There is a bug with the audio samples upon exit (app crashes) which would be a bug in the native code.  i'll try updating to the latest raylib commit and see if that fixes it.

I will publish a nuget package once i get the linux binaries built.

**Comment by jasonswearingen** [comment]
win x64 preview available: https://www.nuget.org/packages/Raylib-CsLo/4.2.0-alpha0
