### ISSUE TITLE
SetWindowPosition overrides WindowSize

### ISSUE THREAD

**Issue by bradmartin333** [NotNotTech/Raylib-CsLo#29]
Have to follow SetWindowPosition with SetWindowSize
```
InitWindow(0, 0, "test");
SetWindowPosition(x, y);
SetWindowSize(wid, hgt);
```
or else the size will revert to some default.

**Comment by jasonswearingen** [comment]
yes sorry that is a raylib (native) issue.  please raise an issue there.
