### ISSUE TITLE
Use branches (or tags) to version your releases

### ISSUE THREAD

**Issue by Auios** [NotNotTech/Raylib-CsLo#3]
Use branches (or tags) to version your releases.
Currently you have only one branch "main"
I'd suggest creating a new branch and name it "4.0.0-rc.3.1" (Whatever your Nuget release version is named)
and use "main" as your development branch where you push all new commits to.
The "4.0.0-rc.3.1" branch and any future release branches should never have new commits after you make your Nuget release.
Also I personally like to rename "main" to "development" bu that's just my personal preference :)

**Comment by Auios** [comment]
Tags are a nice alternative too actually. I forgot about them!

**Comment by jasonswearingen** [comment]
Thanks for the input!  I will be sure to tag everything from now on
