### ISSUE TITLE
Error using GUI functionality on M1 Mac: Unable to find an entry point named 'GuiButton' in shared library 'raylib'

### ISSUE THREAD

**Issue by NathanielBlack** [NotNotTech/Raylib-CsLo#32]
Hi there,

as the title says if I use something like the `RayGui.GuiButton` method I get the following exception: 

`Unable to find an entry point named 'GuiButton' in shared library 'raylib'`

When I comment out the button and leave my other regular raylib draw calls it runs again. 

I am on a M1 Mac running MacOs Ventura 13.2. 
I had to manually place the `libraylib.dylib` file in my Output bin directory to get Raylib working in the first place. However I am not knowledgeable enough to now figure out a way to get the rayguy functionality working. 

I tried the Standalone example from this repository as well. It works after copying the dylib file into the bin directory but it crashes with the same error when I add a button. 

Not sure if this is even an issue with this library per se or just with its documentation as I just can't figure out how to get it to run. 

Thanks in advance!

**Comment by jasonswearingen** [comment]
Are you building from the source code, or using the nuget package?  I think
if you use the nuget you should not need to copy the lib to the output
folder.

For the missing GuiButton, I think this means that the mac dylib was not
built with RayGui.  This is unfortunate.  I didn't build the file as I do
not own a Mac.  You would need to follow the build steps described in the
raylib-cslo repo and build the native mac library with the raylib extras.
 If you do that, could you please send it to me so I can include it in the
nuget package?



 - Jason

**Comment by NathanielBlack** [comment]
[raylib.dylib.m1.zip](https://github.com/NotNotTech/Raylib-CsLo/files/10830516/raylib.dylib.m1.zip)

I managed to get the buttons to work after building the `dylib` files myself following the instructions of this repository. 
I tested it by going to my local nuget cache (`~/.nuget/packages/raylib-cslo/4.2.0.5/runtimes/osx-arm64/native`) and replacing the .dylib files with the ones provided in the zip file and then regularly building the project.
 I did not need to put any additional files in the `bin` directory this way. 

Thank you so much!

**Comment by jasonswearingen** [comment]
published on nuget as `4.2.0.6`

**Comment by NathanielBlack** [comment]
I just wanted to check if it now actually works and it still does not but I figured out the problem. 
3 of the 4 files are just MacOS aliases that point to the one true `dylib` file. When you open this file on your machine with windows and copy the files Windows does not understand the MacOS alias metadata and removes it leaving us with a broken arm-version once again. 
Source: https://stackoverflow.com/questions/21771273/mac-os-x-alias-folder-file-do-not-persist-on-windows

I will try to create a Pull Request with the Windows-untouched alias files and then we should be good.

**Comment by jasonswearingen** [comment]
thanks...  I will try to publish this nuget from windows again, if that doesn't work let me know and I can try to publish the nuget from a linux VM instead.

**Comment by NathanielBlack** [comment]
Alright, just let me know when the package is available and I will try it asap.

**Comment by jasonswearingen** [comment]
ok 4.2.0.7 should be on nuget in a few min.

**Comment by NathanielBlack** [comment]
Sadly we have the same issue again. Crazy. 
Another idea: We delete the 3 aliases and rename the file `libraylib.4.2.0.dylib`to `libraylib.dylib`. Then it is like in the the other OSX folder. That would work at least on my machine, I just tried it.

**Comment by jasonswearingen** [comment]
Hi sorry I made a mistake, I didn't actually merge your change in when I
published!   I just did it properly, so please try out 4.2.0.8 (just
published to nuget)  and if that doesn't work, please go ahead and
delete/rename whatever .dylib you feel is needed.

 - Jason

**Comment by NathanielBlack** [comment]
Hi Jason, 

the issue persisted in the latest release. 
I created another PR that holds the changes described above. I hope with that we can fix it for all MacOS ARM users! 

Tho I am honestly not sure. Maybe release it as a pre-release on NuGet so I can try it and come back with feedback? 

Because with the newest version even non GUI stuff does not work, so we DID change something. Tho the local nuget cache files are not aliases. 
I re-cloned this repo and saw that only 2 of 3 aliases persisted in the files there. So maybe I should rather create a new pull request with the aliases and then you try to publish from a linux machine which hopefully won't break them like windows does?
I have no experience publishing to NuGet but I could also publish from my Mac, but I assume you'd need to trust me with some form of credentials.

**Comment by jasonswearingen** [comment]
sure give me a moment

**Comment by jasonswearingen** [comment]
ok I just published your changes under `4.2.0.9-pre-m1-0` on nuget.    also gave you maintainer access so you can try publishing too. 

For publishing nuget, I guess you will have to figure it out on your platform, but if it helps at all:
-    I build the nuget from visual studio (it's setup config is in the .csproj).  A new nuget gets created every build, using the version number specified in the `.csporj` like `<Version>4.2.0.9-pre-m1-0</Version>`.
- I use a powershell script to publish it  `nuget-deploy.ps1`.    this script is in the same folder as the .csproj

**Comment by NathanielBlack** [comment]
Alright, that actually worked! At least my M1 MacBook running the latest version of MacOS (13.2) seems to work well with the new pre-release you put out. 
Do we want to leave it at that and then come back to it once somebody reports an issue with it?

**Comment by jasonswearingen** [comment]
okay cool!   yes I agree lets just roll with  it!

 I just published `4.2.0.9`
