### ISSUE TITLE
Bug: Can't change text on GuiTextInputBox

### ISSUE THREAD

**Issue by mjones409** [NotNotTech/Raylib-CsLo#35]
Raylib_CsLo.RayGui.GuiTextInputBox(Rectangle bounds, string? title, string? message, string? buttons, string? text, int textMaxSize = 255) should allow for the editing of the text like the overload version of the method. I suggest adding the ref keyword to the string? text parameter.

**Comment by jasonswearingen** [comment]
sorry I don't understand what you mean.  strings are immutable so ref string wouldn't matter?

could you paste a link to the line you are talking about?  and an example showing what your expected behavior is?

**Comment by mjones409** [comment]
If you use the bindings to display a GuiTextInputBox, you can not actually input text. It allows you to click in to it, but not change the text in the box by typing like you can in the C version of raygui. Screenshot below of the code:

![image](https://user-images.githubusercontent.com/56898579/223313244-83734ee1-dfb7-4afa-ac3f-99e2baf224d1.png)

I propose changing all of these bindings where raygui edits the value of the strings and of the ints to be passed by reference and that allows us to keep the functionality and also not have any unsafe methods in the bindings at all unless we want to continue overloading them with sbyte* to keep that option open as well. I've already done the work of converting my code using a library but I do think it would be better if it was baked in to the bindings but I have no idea how to go about autogenerating them so I did it by hand. Here is an example of what I am talking about:

![image](https://user-images.githubusercontent.com/56898579/223313823-9b19f3ba-6e12-4d1b-bcfa-2aa914f3838a.png)

You can pass strings and ints by reference with this ref keyword and it works nicely.

![image](https://user-images.githubusercontent.com/56898579/223313915-7ee2587b-4967-4b23-ba37-322d572d6ef8.png)

**Comment by mjones409** [comment]
Also, these functions crash when passed a null string, but the others don't. 
![image](https://user-images.githubusercontent.com/56898579/223324514-8548f5dd-4216-4744-a2fe-cdb6127fdb7e.png)

I think the C version of raygui can tolerate nulls but I didn't check every function, just a couple. In the case that they can't, I think replacing the 'string?' with 'string' types makes sense so people know not to pass nulls, but the second best thing to do would be this (but I think it could lead to slightly different results between csLo and C):
![image](https://user-images.githubusercontent.com/56898579/223324902-f6bfbb97-f5a9-4d13-a7e8-bc469d55db96.png)

I think the best option would be to replace the spanOwners with code like this:
![image](https://user-images.githubusercontent.com/56898579/223325032-30386d0f-6fff-4bd2-8b22-20f9e97d9ec0.png)

**Comment by jasonswearingen** [comment]
it has been a while since I wrote the string marshaling code, and it's complicated, but works.  A good workaround to your problem seems to be that You should sanitize your inputs prior to calling the raylib functions.

**Comment by tlitookilakin** [comment]
Sanitization only addresses problems with nulls, it does not address the larger problem of strings being immutable.
The string overload for GuiTextInputBox simply does not allow editing at all, which defeats the point of using a text input.
