### ISSUE TITLE
DrawTextRec() or DrawTextBoxed() missing

### ISSUE THREAD

**Issue by acheddadi** [NotNotTech/Raylib-CsLo#4]
It looks like those methods were deprecated, is there anything to replace them?

**Comment by jasonswearingen** [comment]
I suggest you look at the C# examples which include all the text examples, or maybe look at the function explanations found at  https://www.raylib.com/cheatsheet/cheatsheet.html 

Sorry I don't have experience with the text api's you are talking about.
