### ISSUE TITLE
Can we have managed overloads of raygui method's?

### ISSUE THREAD

**Issue by Shadowblitz16** [NotNotTech/Raylib-CsLo#5]
I see raygui takes pointers in alot of its functions can we get managed overloads?
I would prefer not to need to use unsafe and marshaling

**Comment by jasonswearingen** [comment]
That's probably not something I would want to add, as it would be recreating most the entire api, defeating the purpose of auto-gen bindings.

However please paste an example method and what you would ideally like to see as an example managed overload, in case I am misunderstanding your request.

**Comment by Shadowblitz16** [comment]
![image](https://user-images.githubusercontent.com/2453707/154383645-aaa65157-59b4-4df4-8508-d10cf9c2b1e9.png)
one changes the test to a string? but it still has the other parameter that takes pointers.

**Comment by jasonswearingen** [comment]
yeah there is an overload to convert the `sbyte*` to `string`.

For the `int* active` I have no idea what that would be.  writing the proper overload would require usage of the api that I don't have expertise with.

If you have an idea of what would be better, you can submit a PR or just paste the code for a custom overload here and I can check it in.

**Comment by Shadowblitz16** [comment]
ya idk either I can ask ray

**Comment by jasonswearingen** [comment]
will close for now, reopen if needed!
